name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch name
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: web1
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --omit=dev
      
      - name: Remove existing
        run: rm -rf /var/www/domains/softaccel.net/subdomains/zbxwizz/public_html/*

      - name: Copy files
        run: cp -r * /var/www/domains/softaccel.net/subdomains/zbxwizz/public_html

      - name: Remove existing
        run: rm -rf /var/www/domains/zbxwizz.app/subdomains/demo/public_html/*

      - name: Copy files
        run: cp -r * /var/www/domains/zbxwizz.app/subdomains/demo/public_html

      - name: Send Telegram notification
        if: always()  # This ensures the notification is sent even if the job fails
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          message: |
            🚀 <b>Deployment Status</b>
            
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Status: ${{ job.status }}
            
            🔗 <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow</a>

